# Generated by Django 4.2.13 on 2024-07-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userId',
        ),
    ]
